RealEstate/RealEstate/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("", include('CKrealestate.urls')),  # Replace 'your_app' with the name of your app
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RealEstate/CKrealestate/models.py
from django.db import models
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import pre_save
from django.dispatch import receiver



class Property_Type(models.Model):
    property_type_id = models.AutoField(primary_key=True, unique=True)
    property_type_name = models.CharField(max_length=100)

    def __str__(self):
        return self.property_type_name


class Property_Neighborhood(models.Model):
    neighborhood_id = models.AutoField(primary_key=True, unique=True)
    neighborhood_name = models.CharField(max_length=100)

    def __str__(self):
        return self.neighborhood_name


class Property_Status(models.Model):
    property_status_id = models.AutoField(primary_key=True)
    property_status_name = models.CharField(max_length=100)

    def __str__(self):
        return self.property_status_name


class Property_Price_Range(models.Model):
    price_range_id = models.AutoField(primary_key=True, unique=True)
    price_range_value = models.CharField(max_length=100)

    def __str__(self):
        return self.price_range_value


def current_year():
    return datetime.date.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


class Property(models.Model):
    property_id = models.AutoField(primary_key=True, unique=True)
    home_type = models.ForeignKey(Property_Type, on_delete=models.CASCADE, blank=False, null=False)
    neighborhood = models.ForeignKey(Property_Neighborhood, on_delete=models.CASCADE, blank=False, null=False)
    status = models.ForeignKey(Property_Status, on_delete=models.CASCADE, blank=False, null=False)
    price_range = models.ForeignKey(Property_Price_Range, on_delete=models.CASCADE,  blank=False, null=False)
    property_street_address = models.CharField(max_length=100,  blank=False, null=False)
    property_city = models.CharField(max_length=100,  blank=False, null=False)
    property_state = models.CharField(max_length=2,  blank=False, null=False)
    property_zip_code = models.CharField(max_length=10, default='00000',  blank=False, null=False)
    property_price = models.BigIntegerField(blank=False, null=False, validators=[MinValueValidator(0)])
    property_description = models.TextField(max_length=800,  blank=False, null=False)
    property_title = models.CharField(max_length=200,  blank=False, null=False)
    property_area = models.PositiveIntegerField(null=False, blank=False)
    property_year_built = models.PositiveIntegerField(
        default=current_year(), validators=[MinValueValidator(1900), max_value_current_year])
    property_bedroom_count = models.PositiveIntegerField(null=False, blank=False, default=0)
    property_bathroom_count = models.PositiveIntegerField(null=False, blank=False, default=0)
    property_featured = models.BooleanField(default=False)
    property_active = models.BooleanField(default=True)
    property_photo1 = models.ImageField(upload_to='uploads/', null=False, blank=False, default='default_photo.jpg')
    property_photo2 = models.ImageField(upload_to='uploads/', null=True, blank=True)
    property_photo3 = models.ImageField(upload_to='uploads/', null=True, blank=True)
    property_photo4 = models.ImageField(upload_to='uploads/', null=True, blank=True)

    def __int__(self):
        return self.property_id


class Contact(models.Model):
    contact_id = models.AutoField(primary_key=True, unique=True)
    contact_first_name = models.CharField(max_length=100, blank=False, null=False)
    contact_last_name = models.CharField(max_length=100, blank=False, null=False)
    contact_phone = models.CharField(max_length=20,default='(402)000-0000', blank=False, null=False)
    contact_email = models.EmailField(max_length=300, default='example@gmail.com')
    contact_website_link = models.CharField(max_length=200, blank=False, null=False)
    contact_office_street_address = models.CharField(max_length=100, blank=False, null=False)
    contact_office_city = models.CharField(max_length=100, blank=False, null=False)
    contact_office_state = models.CharField(max_length=2, blank=False, null=False)
    contact_office_zip_code = models.CharField(max_length=10, default='00000', blank=False, null=False)
    contact_profile_image = models.ImageField(upload_to='uploads/', null=False , blank=False)
    contact_profile_description = models.TextField(max_length=800, blank=False, null=False)


class Search_Log(models.Model):
    search_log_id = models.AutoField(primary_key=True, unique=True)
    search_date = models.DateField(auto_now_add=True)
    search_home_type = models.ForeignKey(Property_Type, on_delete=models.CASCADE, null=True,blank=True)
    search_neighborhood = models.ForeignKey(Property_Neighborhood, on_delete=models.CASCADE, null=True,blank=True)
    search_price_range = models.ForeignKey(Property_Price_Range, on_delete=models.CASCADE, null=True,blank=True)

    def __int__(self):
        return self.search_log_id

RealEstate/CKrealestate/forms.py
from django import forms
from .models import Property, Contact


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['property_title', 'property_description', 'property_price', 'property_id', 'home_type',
                  'neighborhood', 'status', 'price_range', 'property_street_address', 'property_city', 'property_state',
                  'property_zip_code', 'property_price', 'property_description', 'property_title', 'property_area',
                  'property_year_built', 'property_bedroom_count', 'property_bathroom_count', 'property_active',
                  'property_photo1', 'property_photo2', 'property_photo3', 'property_photo4',
                  ]
        labels = {
            'property_title': 'Property Title (max 100 characters)',
            'property_description': 'Description (max 800 characters)',
            'property_price': 'Price',
            'property_id': 'ID',
            'home_type': 'Home Type',
            'neighborhood': 'Neighborhood',
            'status': 'Status',
            'price_range': 'Price Range',
            'property_street_address': 'Street Address',
            'property_city': 'City',
            'property_state': 'State',
            'property_zip_code': 'Zip Code',
            'property_area': 'Area Square Footage',
            'property_year_built': 'Year Built',
            'property_bedroom_count': 'Bedrooms',
            'property_bathroom_count': 'Bathrooms',
            'property_active': 'Active',
            'property_photo1': 'Photo 1',
            'property_photo2': 'Photo 2',
            'property_photo3': 'Photo 3',
            'property_photo4': 'Photo 4'
        }
        widgets = {
            'property_description': forms.Textarea(attrs={'rows': 5, 'cols': 140}),
            'property_street_address': forms.TextInput(attrs={'style': 'width: 300px;'}),
            'property_state': forms.TextInput(attrs={'style': 'width: 30px;'}),
            'property_zip_code': forms.TextInput(attrs={'style': 'width: 80px;'}),
            'property_title': forms.TextInput(attrs={'style': 'min-width: 500px;'}),
            'property_area': forms.NumberInput(attrs={'style': 'width: 100px;'}),
            'property_year_built': forms.NumberInput(attrs={'style': 'width: 100px;'}),
            'property_bedroom_count':  forms.NumberInput(attrs={'style': 'width: 50px;'}),
            'property_bathroom_count': forms.NumberInput(attrs={'style': 'width: 50px;'}),
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['contact_first_name', 'contact_last_name', 'contact_phone', 'contact_email',
                  'contact_office_street_address', 'contact_office_city', 'contact_office_state',
                  'contact_office_zip_code', 'contact_website_link', 'contact_profile_description',
                  'contact_profile_image',
                  ]

        labels = {'contact_first_name': 'First Name',
                  'contact_last_name': 'Last Name',
                  'contact_phone': 'Phone',
                  'contact_email': 'Email',
                  'contact_office_street_address': 'Office Street Address',
                  'contact_office_city': 'Office City',
                  'contact_office_state': 'Office State',
                  'contact_office_zip_code': 'Office Zip Code',
                  'contact_website_link': 'Office Website Link',
                  'contact_profile_description': 'Profile Bio',
                  'contact_profile_image': 'Profile Image'
                  }

        widgets = {
            'contact_profile_description': forms.Textarea(attrs={'rows': 5, 'cols': 140}),
            'contact_website_link': forms.TextInput(attrs={'style': 'width: 700px;'}),  # Adjust width as needed
            'contact_office_street_address': forms.TextInput(attrs={'style': 'width: 300px;'}),
            'contact_office_state': forms.TextInput(attrs={'style': 'width: 30px;'}),
            'contact_office_zip_code': forms.TextInput(attrs={'style': 'width: 80px;'}),
            'contact_email': forms.TextInput(attrs={'style': 'width: 300px;'}),
            'contact_phone': forms.TextInput(attrs={'style': 'width: 110px;'}),
        }


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)
    email = forms.EmailField(label='Your Email')
    message = forms.CharField(label='Message', widget=forms.Textarea)
    phone = forms.CharField(label='Phone')
    property_id = forms.IntegerField(widget=forms.HiddenInput())

RealEstate/templates/add-property.html
<!-- add-property.html -->

{% extends 'base2.html' %}
{% load static %}

{% block title %}Site Admin Add Property - CK Real Estate{% endblock %}

{% block content %}
    <hr>
    <div class="row">
    <p style="float: right; margin-right: 20px;"> <a href="{% url 'siteadminlanding' %}" class="btn site-admin-btn" style="color: floralwhite;">Back to Main</a></p>
   </div>

     <div class="row">
     
     <div class="col-sm-10" style="margin-left: 200px; margin-top: 30px;">
         <p style="font-size: large"><b>To add a new property listing,</b> please complete all required fields 
             and then click the button labeled <b>'Submit'</b> (fields that have a  <span class="text-danger" style="font-size: larger">*</span> 
             are <b>Required</b>).
                </p>
         <div class="table-container" style="overflow-x: auto;">
        <table class="table" style="border: 5px solid #0073e5;">
            <thead>
                <tr>
                    <th colspan="11" style="text-align: center; background-color: #0073e5; color: white; font-size: 18pt;">
                        Add New Property
                    </th>
                </tr>
            <tr>
                
                <td>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- property fields -->
                <div class="form-group">
                    <label for="id_property_title">{{ property_form.fields.property_title.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_title}}
                </div>
                <div class="form-group">
                    <label for="id_property_street_address">{{ property_form.property_street_address.label}}<span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_street_address }}
                    <label for="id_property_city">{{ property_form.property_city.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_city }}
                    <label for="id_property_state">{{ property_form.property_state.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_state }}
                    <label for="id_property_zip_code">{{ property_form.property_zip_code.label }}<span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_zip_code }}
                </div>
                <div class="form-group">
                    <label for="id_rice_range">{{ property_form.price_range.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.price_range }}
                    <label for="id_property_price">{{ property_form.property_price.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_price }}
                    <label for="id_home_type">{{ property_form.home_type.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.home_type }}
                    <label for="id_neighborhood">{{ property_form.neighborhood.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.neighborhood }}
                    <label for="id_status">{{ property_form.status.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.status }}
                </div>

                  <div class="form-group">
                    <label for="id_property_area">{{ property_form.property_area.label }}<span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_area }}
                    <label for="id_property_year_built">{{ property_form.property_year_built.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_year_built }}
                    <label for="id_property_bedroom_count">{{ property_form.property_bedroom_count.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_bedroom_count }}
                    <label for="id_property_bathroom_count">{{ property_form.property_bathroom_count.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_bathroom_count }}
                    &nbsp; <label for="id_property_active">{{ property_form.property_active.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ property_form.property_active }}
                </div>


                <div class="form-group">
                    <label for="id_property_description">{{ property_form.property_description.label }} <span class="text-danger" style="font-size: larger">*</span></label><br>
                    {{ property_form.property_description }}
                </div>
                <div>
                    <p style="padding-top: 10px; text-align: center; border: 3px solid blue; width: 90%"><b>Note:</b> The photo labeled <b>'Photo 1'</b> will be the main photo displayed for your property. 
                    If your property is marked as featured, it will be the only photo displayed on the Home page.
                    </p>
                </div>
                <div class="form-group" >
                   <p style="display: inline-block"> <label for="id_property_photo1">{{ property_form.property_photo1.label }}  <span class="text-danger" style="font-size: larger">*</span></label>
                       {{ property_form.property_photo1 }}</p>
                    <p style="display: inline-block"><label for="id_property_photo2">{{ property_form.property_photo2.label }}</label>
                        {{ property_form.property_photo2 }}</p>
                   <p style="display: inline-block"> <label for="id_property_photo3">{{ property_form.property_photo3.label }}</label>
                       {{ property_form.property_photo3 }}</p>
                   <p style="display: inline-block"> <label for="id_property_photo4">{{ property_form.property_photo4.label }}</label>
                       {{ property_form.property_photo4 }}</p>
                </div>


               <button type="submit" style="font-size: larger; float: right" href="" class="site-admin-btn" >
               Submit</button>
            </form>
  
                </td>
            </tr>
            </thead>
        </table>
         </div>
     </div>
    </div>

<script>
    // JavaScript code to limit input length
    document.getElementById("id_property_title").addEventListener("input", function() {
        if (this.value.length > 100) {
            this.value = this.value.slice(0, 100);
        }
    });
    
    // JavaScript code to limit input length for property_description
    document.getElementById("id_property_description").addEventListener("input", function() {
        if (this.value.length > 800) {
            this.value = this.value.slice(0, 800);
        }
    });
</script>
{% endblock %}

RealEstate/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div style="display: block">
    <header class="header">
        <div class="row">
            <div class="col-sm-2">
                <img src="{% static "images/logo.png" %}" class="logo" alt="logo" style="margin-left: 10px"/>
            </div>
            <div class="col-sm-8" style="margin-top: 50px; text-align: center; font-size: x-large; font-weight: bold">
                Welcome to CK Real Estate! <br>Explore our listings and discover your dream home today.
            </div>
            <div class="col-sm-2">
                <a class="btn admin-btn" style="float: right" href="{% url 'login' %}">Login</a>
            </div>
        </div>
    </header>
    <div class="row">
        <hr>
    </div>
    <div class="row" style="margin-top: 5px; margin-left: 50px;">

        <div class="menu">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><span>|</span></li>
                <li><a href="{% url 'all_listings' %}">All Listings</a></li>
                <li><span>|</span></li>
                <li>
                    <a href="{% url 'search_all_listings' %}" class="btn-md">
                        Search All Listings
                    </a></li>
                <li><span>|</span></li>
                <li><a href="{% url 'profile' %}">Profile</a></li>
                <li><span>|</span></li>
                <li><a href="{% url 'omahalinks' %}">Omaha Links</a></li>
            </ul>
        </div>

    </div>

    <main>
        {% block content %}{% endblock %}
    </main>
<div>

    <footer style="text-align: center; bottom: 10px; width: 100%;">
        <hr>
        <i class="fa fa-copyright" aria-hidden="true"></i> 2024 All Listings, LLC. All rights reserved.
    </footer>
</div>


</div>
</body>
</html>

RealEstate/templates/contact-realtor.html
<!-- contact-realtor.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact Realtor - CK Real Estate{% endblock %}

{% block content %}

<div class="container">
 <div class="row">
    <div class="col-sm-10 col-md-10 col-lg-12" style="padding-top: 40px; overflow-x: auto">
      {% if error_message %}
          <p class="text-danger"><b>{{ error_message }}</b></p>
    {% endif %}
        <table class="table" style="border: 5px solid #0073e5;">
            <form method="post" action="{% url 'contact_realtor' %}">
                    {% csrf_token %}
            <thead>
                <tr>
                    <th colspan="11" style="text-align: center; background-color: #0073e5; color: white; font-size: 18pt;">
                        Contact Realtor
                    </th>
                </tr>
                <tr>
                    <td colspan="3">
                        <p style="font-size: 15px; padding-left: 10px;">  <b>To send an email to the Realtor,
                        </b> please complete all required fields below and then click the <b>'Send Email'</b> button
                         (fields that have a <span class="text-danger" style="font-size: larger">*</span> are <b>Required</b>).
                </p>
                    </td>
                </tr>
                <tr>
              
                        <td>        
                        <label for="id_name">Name <span class="text-danger">*</span></label>
                        <input type="text" maxlength="50" style="width: 300px" id="id_name" name="name" value="{{ name }}">
                        </td>
                        <td>
                        <label for="id_phone">Phone <span class="text-danger">*</span></label>
                        <input type="tel" id="id_phone" name="phone" value="{{ phone }}">
                        </td>
                        <td>
                        <label for="id_email">Email <span class="text-danger">*</span></label>
                        <input type="email" style="width: 400px" id="id_email" name="email" value="{{ email }}">
                        </td>
                 </tr> 
                    <tr>
                        <td colspan="3">   
                        <label for="id_body">Comments/Questions <span class="text-danger">*</span></label>
                        <textarea id="id_body" name="body" rows="7" cols="115">{{ body }}</textarea>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3">
                    <button type="submit" class="admin-btn" style="float: right; background-color: #0073e5; color: white;">Send Email</button>
                        </td>
                    </tr>
                  </thead>
                </form>
            </table>
        </div>
    </div>
</div>
{% endblock %}

RealEstate/templates/share-property.html
<!-- share-property.html -->

{% extends 'base.html' %}

{% block title %}Contact Realtor About Property - CK Real Estate{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-10 col-md-10 col-lg-12" style="padding-top: 40px;">

            {% if error_message %}
                <p class="text-danger"><b>{{ error_message }}</b></p>
            {% endif %}

            <form method="post" action="{% url 'share_property' property_id=item.property_id %}">
                {% csrf_token %}
                <table class="table" style="border: 5px solid #0073e5; width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="11" style="text-align: center; background-color: #0073e5; color: white; font-size: 18pt;">
                                Contact Realtor About:<br> {{ item.property_title }}
                            </th>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <p style="font-size: 15px;">Please complete all required fields below and then click the <b>'Send Email'</b> button
                         (fields that have a <span class="text-danger" style="font-size: larger">*</span> are <b>Required</b>).</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="name">Name <span class="text-danger">*</span></label>
                                <input type="text" style="width: 300px;" id="name" name="name" value="{{ name }}" required>
                            </td>
                            <td>
                                <label for="id_phone">Phone <span class="text-danger">*</span></label>
                                <input type="tel" id="id_phone" name="phone" value="{{ phone }}">
                            </td>
                            <td colspan="2">
                                <label for="id_email">Email <span class="text-danger">*</span></label>
                                <input type="email" id="id_email" name="email" value="{{ email }}" style="width: 400px;" required>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <label for="property_link">Property Link</label>
                                <input type="text" id="property_link" name="property_link" style="width: 500px;" readonly disabled>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <label for="message">Message <span class="text-danger">*</span></label><br>
                                <textarea id="message" name="message" rows="8" cols="115" required></textarea>
                            </td>
                        </tr>

                        <tr>
                            <input type="hidden" id="property_id" name="property_id" value="{{ item.property_id }}">
                        </tr>

                        <tr>
                            <td colspan="3">
                                <button type="submit" class="admin-btn" style="float: right; background-color: #0073e5; color: white;">Send Email</button>
                            </td>
                        </tr>
                    </thead>
                </table>
            </form>
        </div>
    </div>
</div>

<script>
    function generatePropertyLink() {
        const propertyId = document.getElementById('property_id').value.trim();
        const baseUrl = '{{ base_url }}';
        document.getElementById('property_link').value = `${baseUrl}property-details/${propertyId}`;
    }
    document.addEventListener('DOMContentLoaded', function() {
        generatePropertyLink();
    });
</script>
{% endblock %}

RealEstate/templates/update-profile.html
<!-- update-profile.html -->

{% extends 'base2.html' %}
{% load static %}

{% block title %}Site Admin Update Profile - CK Real Estate{% endblock %}

{% block content %}
    <hr>
    <div class="row">
    <p style="float: right; margin-right: 20px;"> <a href="{% url 'siteadminlanding' %}" class="btn site-admin-btn" style="color: floralwhite;">Back to Main</a></p>
   </div>

    <div class="row" style="overflow-x:auto;">
     
     <div class="col-sm-10" style="margin-left: 200px; margin-top: 30px; width: 75%;">
         <p style="font-size: large"><b>To add/edit your profile,</b> please update the field(s) listed below 
             and then click the button labeled <b>'Submit'</b> (fields that have a  <span class="text-danger" style="font-size: larger">*</span> 
             are <b>Required</b>).
                </p>
        <table class="table" style="border: 5px solid #0073e5;">
            <thead>
                <tr>
                    <th colspan="11" style="text-align: center; background-color: #0073e5; color: white; font-size: 18pt;">
                        Add/Update Profile
                    </th>
                </tr>
            <tr>
                <td>
                 <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                 <div class="form-group">
                    <label for="id_first_name">{{ form.fields.contact_first_name.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_first_name}}
                      <label for="id_first_name">{{ form.fields.contact_last_name.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_last_name}}
                     <label for="id_phone">{{ form.fields.contact_phone.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_phone}}<br><br>
                     <label for="id_email">{{ form.fields.contact_email.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_email}}
                 </div>
                </td> 
            </tr>
            <tr>
                <td>        
                 <div class="form-group">
                    <label for="id_address">{{ form.fields.contact_office_street_address.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_office_street_address}}
                      <label for="id_city">{{ form.fields.contact_office_city.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_office_city}}
                     <label for="id_state">{{ form.fields.contact_office_state.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_office_state}}
                     <label for="id_zip">{{ form.fields.contact_office_zip_code.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_office_zip_code}}
                </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                    <label for="id_weblink">{{ form.fields.contact_website_link.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    {{ form.contact_website_link}}
                    </div>    
                </td>
            </tr>    
             <tr>
                <td>
                    <div class="form-group">
                    <label for="id_bio">{{ form.fields.contact_profile_description.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    <br>{{ form.contact_profile_description}}
                    </div>    
                </td>
            </tr>  
            <tr>
                <td>
                    <div class="form-group">
                    <label for="id_image">{{ form.fields.contact_profile_image.label }} <span class="text-danger" style="font-size: larger">*</span></label>
                    <br>{{ form.contact_profile_image}}
                    </div>    
                </td>
            </tr> 
            <tr>  
                <td>
                <button type="submit" style="font-size: larger; float: right" href="" class="site-admin-btn" >
               Submit</button>
               
                </form>
                </td>
            </tr>
            </thead>
        </table>
     </div>
    </div>
{% endblock %}